name: listing
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Core
  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.7
  flutter_displaymode: ^0.6.0
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  auto_route: ^9.2.2
  upgrader: ^11.3.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.3
  connectivity_plus: ^6.0.3
  json_annotation: ^4.9.0
  flutter_native_splash: ^2.4.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  get_it: ^8.0.0

  #Ui
  remixicon: ^1.2.0
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  country_codes: ^3.1.0+2
  flutter_svg: ^2.0.10+1
  pull_to_refresh: ^2.0.0
  top_snackbar_flutter: ^3.1.0
  image_picker: ^1.1.2
  country_flags: ^3.0.0
  photo_view: ^0.15.0
  roundcheckbox: ^2.0.5
  flutter_datetime_picker_plus: ^2.2.0
  flutter_inappwebview: ^6.1.5
  flutter_advanced_switch: ^3.1.0
  url_launcher: ^6.3.0
  cached_network_image: ^3.3.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  flutter_login_facebook: ^2.0.1
  crypto: ^3.0.3
  share_plus: ^10.0.0

  #Firebase
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  firebase_performance: ^0.10.0+3
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  firebase_messaging: ^15.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/translations/
